### ISSUE TITLE
Kvantum theme

### ISSUE THREAD

**Issue by CPyJIb** [PapirusDevelopmentTeam/papirus-qtcurve-theme#1]
So what about using kvantum instead/in parallel with qtcurve? Little buttons and buggy radio buttons makes me sad

**Comment by varlesh** [comment]
I don't know about Kvantum, because have some nuances:
1. I'm not found transparenty on window, yes context menu have this option, but window not. QtCurve have option for opacity (windows, dialogs and menus)
2. How disable menubar? On QtCurve this working with hot key Ctrl+Alt+M
Also, Papirus plasma theme - this mod Breeze Plasma Theme with some colors and little changes and Papirus start created for Breeze engine (because i's default for KDE)... If  i make new Kvantum style i need remake many elements on Plasma theme and not sure how looking will be nwe Plasma Theme...
Or another way - mod Dynamo style for Papirus. But, it's realy needed? Dynamo have little changes with Breeze style, i don't know whether do it.
For example, Dynamo (with gray mod)
left Kvantum - right Breeze
![screenshot_20160608_230448](https://cloud.githubusercontent.com/assets/8083855/15909596/a8c80aea-2dcf-11e6-8b60-2b6e4f809bb6.png)

Sorry my bad English ))

**Comment by varlesh** [comment]
Transparent working, i found this - it's option "Translucent windows".
This very good )

**Comment by varlesh** [comment]
I'm create Kvantum theme on future, if anybody have wish - please tell me.

**Comment by varlesh** [comment]
Looking very good ))
![screenshot_20160609_001906](https://cloud.githubusercontent.com/assets/8083855/15911290/d4771976-2dd7-11e6-9a78-572d350865bb.png)

**Comment by CPyJIb** [comment]
Show/hide menubar - ctrl+m

**Comment by varlesh** [comment]
@CPyJIb This not working for non-KDE apps :(
I make this, need somes enhancement:
![screenshot_20160609_131419](https://cloud.githubusercontent.com/assets/8083855/15926366/53807f02-2e44-11e6-867c-f3e257cd0d69.png)

**Comment by CPyJIb** [comment]
Not bad, but I think that buttons on top might be more closer to window color. And yeah, kvantum also have right click menu style, evolvere light theme have pretty nice style
![image](https://cloud.githubusercontent.com/assets/7214361/15928189/26a87f0c-2e4e-11e6-8b18-5ccd5c616ab0.png)

**Comment by varlesh** [comment]
i create context menu
![screenshot_20160609_144230](https://cloud.githubusercontent.com/assets/8083855/15928597/78bea382-2e50-11e6-922a-d475bbb8eea5.png)

**Comment by varlesh** [comment]
https://github.com/PapirusDevelopmentTeam/papirus-kvantum-theme/commit/c2a7915158da67a213f28a66f3245281cfb04707
